'use strict';

var app = angular.module('inspinia');

app.controller('PersonnelCtrl', ['$scope', 'modalSvc', function ($scope, modalSvc) {

     $scope.message = 'message for Personnel';
     $scope.personnelList = getFakePersonnelList();
     $scope.currentPage = 1;
     $scope.pageSize = 10;
     $scope.templateUrl = '/views/management/personnelDetail.html';
     $scope.controllerName = 'PersonnelDetailCtrl';

     $scope.openPersonnelDetails = function (personnel) {

         var clone = JSON.parse(JSON.stringify(personnel));
      

         modalSvc.openModal($scope.onSaveCallFromModal, $scope.onCancelCallFromModal, $scope.templateUrl, $scope.controllerName, clone, personnel, null);

     };

     $scope.onSaveCallFromModal = function (personnelMofified) {

         //Post the modified object to server. 
         if (personnelMofified.id == -1) {
             //new personnel
         } else {
             //modify exsiting
         }
         

     };

     $scope.onCancelCallFromModal = function () {
         // do nothing. 
     };


     $scope.addNew = function () {
         var newPersonnel = {id:-1, Gender:'Male'};

         modalSvc.openModal($scope.onSaveCallFromModal, $scope.onCancelCallFromModal, $scope.templateUrl, $scope.controllerName, newPersonnel, null, null);
    };

}]);

function getFakePersonnelList()
{

    var list = [{
        "id": 1,
        "Gender": "Female",
        "FirstName": "Carol",
        "LastName": "Robinson",
        "PreferredName": "Nancy",
        "Email": "nrobinson0@spotify.com",
        "Mobile": "7-(285)587-6053",
        "DateOfBirth": "12/04/1993"
    }, {
        "id": 2,
        "Gender": "Female",
        "FirstName": "Annie",
        "LastName": "Chapman",
        "Email": "rchapman1@wisc.edu",
        "Mobile": "9-(337)737-3614"
    }, {
        "id": 3,
        "Gender": "Female",
        "FirstName": "Frances",
        "LastName": "Armstrong",
        "Email": "aarmstrong2@etsy.com",
        "Mobile": "7-(771)801-7969"
    }, {
        "id": 4,
        "Gender": "Female",
        "FirstName": "Norma",
        "LastName": "Watson",
        "PreferredName": "Kathy",
        "Email": "kwatson3@google.co.uk",
        "DateOfBirth": "23/09/1998"
    }, {
        "id": 5,
        "Gender": "Female",
        "FirstName": "Jane",
        "LastName": "Gilbert",
        "Email": "sgilbert4@geocities.jp",
        "Mobile": "4-(421)749-2713"
    }, {
        "id": 6,
        "Gender": "Male",
        "FirstName": "Joe",
        "LastName": "Bailey",
        "PreferredName": "Jason",
        "Email": "jbailey5@globo.com",
        "DateOfBirth": "14/02/1999"
    }, {
        "id": 7,
        "Gender": "Male",
        "FirstName": "Eric",
        "LastName": "Jackson",
        "PreferredName": "Eugene",
        "Email": "ejackson6@arizona.edu",
        "Mobile": "6-(133)408-2367",
        "DateOfBirth": "13/07/1992"
    }, {
        "id": 8,
        "Gender": "Female",
        "FirstName": "Tammy",
        "LastName": "Williamson",
        "Email": "awilliamson7@ning.com",
        "Mobile": "6-(903)739-9948"
    }, {
        "id": 9,
        "Gender": "Female",
        "FirstName": "Judy",
        "LastName": "Marshall",
        "PreferredName": "Anna",
        "Email": "amarshall8@nytimes.com",
        "Mobile": "0-(632)628-0336",
        "DateOfBirth": "16/06/1982"
    }, {
        "id": 10,
        "Gender": "Female",
        "FirstName": "Helen",
        "LastName": "Mcdonald",
        "Email": "pmcdonald9@sfgate.com"
    }, {
        "id": 11,
        "Gender": "Female",
        "FirstName": "Debra",
        "LastName": "Richards",
        "Email": "hrichardsa@pinterest.com",
        "Mobile": "7-(578)728-0247"
    }, {
        "id": 12,
        "Gender": "Male",
        "FirstName": "Jeremy",
        "LastName": "Lane",
        "Email": "glaneb@deliciousdays.com",
        "Mobile": "4-(974)652-2473"
    }, {
        "id": 13,
        "Gender": "Male",
        "FirstName": "Douglas",
        "LastName": "Bennett",
        "Email": "bbennettc@merriam-webster.com"
    }, {
        "id": 14,
        "Gender": "Male",
        "FirstName": "Russell",
        "LastName": "Carroll",
        "Email": "tcarrolld@homestead.com",
        "Mobile": "9-(333)666-5240"
    }, {
        "id": 15,
        "Gender": "Female",
        "FirstName": "Carol",
        "LastName": "Ferguson",
        "PreferredName": "Sharon",
        "Email": "sfergusone@symantec.com",
        "Mobile": "8-(887)198-5210",
        "DateOfBirth": "21/12/1981"
    }, {
        "id": 16,
        "Gender": "Female",
        "FirstName": "Linda",
        "LastName": "Williamson",
        "PreferredName": "Judith",
        "Email": "jwilliamsonf@pbs.org",
        "Mobile": "6-(352)892-7585",
        "DateOfBirth": "16/08/1990"
    }, {
        "id": 17,
        "Gender": "Male",
        "FirstName": "Steve",
        "LastName": "Kennedy",
        "PreferredName": "John",
        "Email": "jkennedyg@buzzfeed.com",
        "Mobile": "9-(174)449-4401",
        "DateOfBirth": "21/07/1988"
    }, {
        "id": 18,
        "Gender": "Male",
        "FirstName": "Joshua",
        "LastName": "Campbell",
        "Email": "rcampbellh@squarespace.com",
        "Mobile": "1-(107)563-5823"
    }, {
        "id": 19,
        "Gender": "Female",
        "FirstName": "Mildred",
        "LastName": "Ramos",
        "PreferredName": "Rachel",
        "Email": "rramosi@uol.com.br",
        "Mobile": "3-(010)521-9400",
        "DateOfBirth": "03/11/1987"
    }, {
        "id": 20,
        "Gender": "Female",
        "FirstName": "Annie",
        "LastName": "Payne",
        "PreferredName": "Barbara",
        "Email": "bpaynej@google.co.jp",
        "Mobile": "1-(150)127-1242",
        "DateOfBirth": "06/08/1992"
    }, {
        "id": 21,
        "Gender": "Male",
        "FirstName": "Samuel",
        "LastName": "Carr",
        "Email": "jcarrk@lulu.com",
        "Mobile": "9-(772)890-5335"
    }, {
        "id": 22,
        "Gender": "Female",
        "FirstName": "Teresa",
        "LastName": "Diaz",
        "PreferredName": "Paula",
        "Email": "pdiazl@skype.com",
        "Mobile": "6-(420)856-3001",
        "DateOfBirth": "06/04/1993"
    }, {
        "id": 23,
        "Gender": "Male",
        "FirstName": "Randy",
        "LastName": "Gomez",
        "PreferredName": "Peter",
        "Email": "pgomezm@cpanel.net",
        "Mobile": "9-(603)421-8691",
        "DateOfBirth": "09/02/1983"
    }, {
        "id": 24,
        "Gender": "Female",
        "FirstName": "Kathryn",
        "LastName": "Collins",
        "PreferredName": "Tammy",
        "Email": "tcollinsn@nba.com",
        "DateOfBirth": "28/12/1990"
    }, {
        "id": 25,
        "Gender": "Male",
        "FirstName": "Michael",
        "LastName": "Armstrong",
        "PreferredName": "Raymond",
        "Email": "rarmstrongo@yandex.ru",
        "DateOfBirth": "21/01/1993"
    }, {
        "id": 26,
        "Gender": "Female",
        "FirstName": "Kelly",
        "LastName": "Boyd",
        "PreferredName": "Christina",
        "Email": "cboydp@narod.ru",
        "Mobile": "8-(944)697-8742",
        "DateOfBirth": "14/02/1997"
    }, {
        "id": 27,
        "Gender": "Female",
        "FirstName": "Frances",
        "LastName": "Burns",
        "Email": "cburnsq@1688.com",
        "Mobile": "9-(029)960-4493"
    }, {
        "id": 28,
        "Gender": "Male",
        "FirstName": "Joseph",
        "LastName": "Rose",
        "Email": "croser@comsenz.com",
        "Mobile": "5-(427)318-2153"
    }, {
        "id": 29,
        "Gender": "Male",
        "FirstName": "Wayne",
        "LastName": "Medina",
        "PreferredName": "George",
        "Email": "gmedinas@bbc.co.uk",
        "Mobile": "9-(200)829-1258",
        "DateOfBirth": "13/09/1991"
    }, {
        "id": 30,
        "Gender": "Male",
        "FirstName": "Roger",
        "LastName": "Jordan",
        "PreferredName": "Gerald",
        "Email": "gjordant@multiply.com",
        "Mobile": "8-(734)794-7985",
        "DateOfBirth": "19/05/1992"
    }, {
        "id": 31,
        "Gender": "Male",
        "FirstName": "Joe",
        "LastName": "King",
        "PreferredName": "Aaron",
        "Email": "akingu@webeden.co.uk",
        "Mobile": "5-(578)921-2575",
        "DateOfBirth": "05/12/1995"
    }, {
        "id": 32,
        "Gender": "Female",
        "FirstName": "Robin",
        "LastName": "Arnold",
        "Email": "marnoldv@abc.net.au",
        "Mobile": "5-(278)002-4431"
    }, {
        "id": 33,
        "Gender": "Female",
        "FirstName": "Janice",
        "LastName": "Dean",
        "PreferredName": "Ruby",
        "Email": "rdeanw@angelfire.com",
        "Mobile": "1-(136)494-8683",
        "DateOfBirth": "12/07/1989"
    }, {
        "id": 34,
        "Gender": "Male",
        "FirstName": "Justin",
        "LastName": "Montgomery",
        "PreferredName": "Kevin",
        "Email": "kmontgomeryx@xing.com",
        "DateOfBirth": "21/12/1996"
    }, {
        "id": 35,
        "Gender": "Female",
        "FirstName": "Anna",
        "LastName": "Wright",
        "PreferredName": "Cheryl",
        "Email": "cwrighty@addthis.com",
        "DateOfBirth": "03/11/1994"
    }, {
        "id": 36,
        "Gender": "Male",
        "FirstName": "Russell",
        "LastName": "Gilbert",
        "PreferredName": "Jonathan",
        "Email": "jgilbertz@apache.org",
        "Mobile": "4-(299)126-9017",
        "DateOfBirth": "04/08/1987"
    }, {
        "id": 37,
        "Gender": "Female",
        "FirstName": "Karen",
        "LastName": "Ford",
        "PreferredName": "Kathleen",
        "Email": "kford10@ovh.net",
        "Mobile": "8-(089)605-4053",
        "DateOfBirth": "19/12/1981"
    }, {
        "id": 38,
        "Gender": "Male",
        "FirstName": "Gary",
        "LastName": "Johnson",
        "PreferredName": "Jesse",
        "Email": "jjohnson11@ask.com",
        "DateOfBirth": "18/07/1984"
    }, {
        "id": 39,
        "Gender": "Female",
        "FirstName": "Judy",
        "LastName": "Kelly",
        "Email": "jkelly12@wikia.com",
        "Mobile": "3-(167)897-5267"
    }, {
        "id": 40,
        "Gender": "Female",
        "FirstName": "Janet",
        "LastName": "Kelly",
        "Email": "mkelly13@google.ca",
        "Mobile": "1-(282)229-2894"
    }, {
        "id": 41,
        "Gender": "Male",
        "FirstName": "Gary",
        "LastName": "Robertson",
        "Email": "nrobertson14@nationalgeographic.com",
        "Mobile": "1-(094)583-2675"
    }, {
        "id": 42,
        "Gender": "Male",
        "FirstName": "Dennis",
        "LastName": "Thompson",
        "Email": "mthompson15@symantec.com",
        "Mobile": "6-(591)607-6038"
    }, {
        "id": 43,
        "Gender": "Male",
        "FirstName": "Steve",
        "LastName": "Hughes",
        "Email": "ahughes16@homestead.com",
        "Mobile": "5-(597)827-9690"
    }, {
        "id": 44,
        "Gender": "Male",
        "FirstName": "Andrew",
        "LastName": "Taylor",
        "PreferredName": "Larry",
        "Email": "ltaylor17@rakuten.co.jp",
        "Mobile": "4-(705)025-2341",
        "DateOfBirth": "11/08/1992"
    }, {
        "id": 45,
        "Gender": "Male",
        "FirstName": "Robert",
        "LastName": "King",
        "PreferredName": "James",
        "Email": "jking18@icio.us",
        "Mobile": "3-(912)573-6221",
        "DateOfBirth": "24/08/1993"
    }, {
        "id": 46,
        "Gender": "Male",
        "FirstName": "Steven",
        "LastName": "Graham",
        "PreferredName": "Jack",
        "Email": "jgraham19@rambler.ru",
        "Mobile": "8-(871)918-5825",
        "DateOfBirth": "20/09/1984"
    }, {
        "id": 47,
        "Gender": "Female",
        "FirstName": "Rose",
        "LastName": "Medina",
        "PreferredName": "Stephanie",
        "Email": "smedina1a@blogs.com",
        "Mobile": "6-(993)977-7467",
        "DateOfBirth": "20/09/1996"
    }, {
        "id": 48,
        "Gender": "Male",
        "FirstName": "Gary",
        "LastName": "Howard",
        "PreferredName": "Ryan",
        "Email": "rhoward1b@zimbio.com",
        "DateOfBirth": "11/08/1981"
    }, {
        "id": 49,
        "Gender": "Male",
        "FirstName": "Brian",
        "LastName": "Harrison",
        "Email": "nharrison1c@devhub.com"
    }, {
        "id": 50,
        "Gender": "Female",
        "FirstName": "Andrea",
        "LastName": "Ramirez",
        "Email": "eramirez1d@npr.org",
        "Mobile": "6-(787)250-7215"
    }, {
        "id": 51,
        "Gender": "Male",
        "FirstName": "Eric",
        "LastName": "Weaver",
        "PreferredName": "Steve",
        "Email": "sweaver1e@yellowpages.com",
        "Mobile": "6-(975)929-5201",
        "DateOfBirth": "15/01/1988"
    }, {
        "id": 52,
        "Gender": "Female",
        "FirstName": "Robin",
        "LastName": "Griffin",
        "Email": "jgriffin1f@tinypic.com",
        "Mobile": "7-(046)401-1636"
    }, {
        "id": 53,
        "Gender": "Male",
        "FirstName": "Ryan",
        "LastName": "Hayes",
        "PreferredName": "Shawn",
        "Email": "shayes1g@freewebs.com",
        "Mobile": "1-(284)855-0573",
        "DateOfBirth": "29/03/1999"
    }, {
        "id": 54,
        "Gender": "Male",
        "FirstName": "Charles",
        "LastName": "Riley",
        "PreferredName": "Bobby",
        "Email": "briley1h@163.com",
        "Mobile": "0-(109)525-4886",
        "DateOfBirth": "10/11/1986"
    }, {
        "id": 55,
        "Gender": "Female",
        "FirstName": "Rebecca",
        "LastName": "Williams",
        "Email": "wwilliams1i@cocolog-nifty.com",
        "Mobile": "5-(999)520-0441"
    }, {
        "id": 56,
        "Gender": "Female",
        "FirstName": "Sharon",
        "LastName": "Mills",
        "PreferredName": "Kelly",
        "Email": "kmills1j@tuttocitta.it",
        "Mobile": "7-(116)252-9097",
        "DateOfBirth": "11/09/1998"
    }, {
        "id": 57,
        "Gender": "Female",
        "FirstName": "Kathy",
        "LastName": "Stewart",
        "Email": "mstewart1k@goodreads.com",
        "Mobile": "5-(366)188-5713"
    }, {
        "id": 58,
        "Gender": "Female",
        "FirstName": "Betty",
        "LastName": "Miller",
        "Email": "amiller1l@cocolog-nifty.com",
        "Mobile": "8-(262)265-4232"
    }, {
        "id": 59,
        "Gender": "Female",
        "FirstName": "Gloria",
        "LastName": "Fernandez",
        "Email": "cfernandez1m@vistaprint.com",
        "Mobile": "9-(838)931-7815"
    }, {
        "id": 60,
        "Gender": "Male",
        "FirstName": "Richard",
        "LastName": "Jackson",
        "PreferredName": "Victor",
        "Email": "vjackson1n@pinterest.com",
        "Mobile": "8-(815)846-2717",
        "DateOfBirth": "28/11/1997"
    }, {
        "id": 61,
        "Gender": "Female",
        "FirstName": "Donna",
        "LastName": "Lane",
        "Email": "elane1o@networkadvertising.org",
        "Mobile": "3-(371)462-2903"
    }, {
        "id": 62,
        "Gender": "Female",
        "FirstName": "Kimberly",
        "LastName": "Rose",
        "PreferredName": "Deborah",
        "Email": "drose1p@webnode.com",
        "Mobile": "6-(503)530-3739",
        "DateOfBirth": "21/05/1990"
    }, {
        "id": 63,
        "Gender": "Female",
        "FirstName": "Helen",
        "LastName": "Shaw",
        "Email": "jshaw1q@prnewswire.com"
    }, {
        "id": 64,
        "Gender": "Female",
        "FirstName": "Teresa",
        "LastName": "Hunter",
        "PreferredName": "Doris",
        "Email": "dhunter1r@mlb.com",
        "Mobile": "9-(168)647-5886",
        "DateOfBirth": "26/09/1996"
    }, {
        "id": 65,
        "Gender": "Female",
        "FirstName": "Frances",
        "LastName": "Reyes",
        "Email": "breyes1s@twitpic.com",
        "Mobile": "7-(379)683-4468"
    }, {
        "id": 66,
        "Gender": "Male",
        "FirstName": "Jeremy",
        "LastName": "Nichols",
        "Email": "anichols1t@umich.edu",
        "Mobile": "9-(911)723-1138"
    }, {
        "id": 67,
        "Gender": "Female",
        "FirstName": "Cheryl",
        "LastName": "Fox",
        "PreferredName": "Diane",
        "Email": "dfox1u@blogger.com",
        "DateOfBirth": "10/08/1998"
    }, {
        "id": 68,
        "Gender": "Male",
        "FirstName": "Aaron",
        "LastName": "Rogers",
        "Email": "jrogers1v@gov.uk",
        "Mobile": "0-(099)056-9454"
    }, {
        "id": 69,
        "Gender": "Male",
        "FirstName": "Harold",
        "LastName": "Torres",
        "PreferredName": "Ryan",
        "Email": "rtorres1w@usgs.gov",
        "DateOfBirth": "11/02/1984"
    }, {
        "id": 70,
        "Gender": "Male",
        "FirstName": "Robert",
        "LastName": "Austin",
        "PreferredName": "Willie",
        "Email": "waustin1x@imageshack.us",
        "Mobile": "8-(822)346-0795",
        "DateOfBirth": "06/07/1985"
    }, {
        "id": 71,
        "Gender": "Female",
        "FirstName": "Ruth",
        "LastName": "Sanders",
        "PreferredName": "Pamela",
        "Email": "psanders1y@zimbio.com",
        "DateOfBirth": "04/08/1982"
    }, {
        "id": 72,
        "Gender": "Female",
        "FirstName": "Alice",
        "LastName": "Sims",
        "Email": "csims1z@edublogs.org",
        "Mobile": "8-(000)124-4075"
    }, {
        "id": 73,
        "Gender": "Female",
        "FirstName": "Gloria",
        "LastName": "Burton",
        "PreferredName": "Wanda",
        "Email": "wburton20@un.org",
        "Mobile": "7-(770)203-3740",
        "DateOfBirth": "18/05/1994"
    }, {
        "id": 74,
        "Gender": "Male",
        "FirstName": "Anthony",
        "LastName": "Wallace",
        "PreferredName": "Thomas",
        "Email": "twallace21@apache.org",
        "Mobile": "2-(019)104-6197",
        "DateOfBirth": "15/03/1988"
    }, {
        "id": 75,
        "Gender": "Female",
        "FirstName": "Kimberly",
        "LastName": "Foster",
        "PreferredName": "Jane",
        "Email": "jfoster22@boston.com",
        "Mobile": "7-(029)453-7967",
        "DateOfBirth": "13/04/1996"
    }, {
        "id": 76,
        "Gender": "Female",
        "FirstName": "Frances",
        "LastName": "Black",
        "Email": "kblack23@ocn.ne.jp",
        "Mobile": "8-(842)144-8251"
    }, {
        "id": 77,
        "Gender": "Female",
        "FirstName": "Catherine",
        "LastName": "Hughes",
        "PreferredName": "Melissa",
        "Email": "mhughes24@illinois.edu",
        "Mobile": "5-(070)063-0479",
        "DateOfBirth": "25/05/1997"
    }, {
        "id": 78,
        "Gender": "Male",
        "FirstName": "Brian",
        "LastName": "Bowman",
        "PreferredName": "Victor",
        "Email": "vbowman25@purevolume.com",
        "Mobile": "8-(928)669-2065",
        "DateOfBirth": "28/08/1983"
    }, {
        "id": 79,
        "Gender": "Male",
        "FirstName": "Ernest",
        "LastName": "Clark",
        "Email": "eclark26@icq.com",
        "Mobile": "7-(847)419-4565"
    }, {
        "id": 80,
        "Gender": "Female",
        "FirstName": "Judith",
        "LastName": "Perkins",
        "Email": "rperkins27@google.fr",
        "Mobile": "5-(764)019-2396"
    }, {
        "id": 81,
        "Gender": "Female",
        "FirstName": "Ruby",
        "LastName": "Davis",
        "Email": "wdavis28@utexas.edu",
        "Mobile": "2-(054)051-7818"
    }, {
        "id": 82,
        "Gender": "Female",
        "FirstName": "Bonnie",
        "LastName": "Gibson",
        "PreferredName": "Teresa",
        "Email": "tgibson29@netvibes.com",
        "Mobile": "7-(655)753-1840",
        "DateOfBirth": "16/11/1986"
    }, {
        "id": 83,
        "Gender": "Male",
        "FirstName": "Justin",
        "LastName": "Coleman",
        "PreferredName": "Andrew",
        "Email": "acoleman2a@illinois.edu",
        "Mobile": "1-(042)124-6303",
        "DateOfBirth": "18/05/1991"
    }, {
        "id": 84,
        "Gender": "Female",
        "FirstName": "Tammy",
        "LastName": "Gomez",
        "Email": "mgomez2b@hhs.gov"
    }, {
        "id": 85,
        "Gender": "Female",
        "FirstName": "Amy",
        "LastName": "Hill",
        "Email": "lhill2c@ovh.net",
        "Mobile": "1-(084)281-8016"
    }, {
        "id": 86,
        "Gender": "Female",
        "FirstName": "Judy",
        "LastName": "Greene",
        "PreferredName": "Heather",
        "Email": "hgreene2d@instagram.com",
        "Mobile": "4-(316)611-9885",
        "DateOfBirth": "06/01/1991"
    }, {
        "id": 87,
        "Gender": "Female",
        "FirstName": "Marie",
        "LastName": "Ross",
        "PreferredName": "Stephanie",
        "Email": "sross2e@census.gov",
        "DateOfBirth": "28/06/1996"
    }, {
        "id": 88,
        "Gender": "Female",
        "FirstName": "Bonnie",
        "LastName": "Riley",
        "PreferredName": "Dorothy",
        "Email": "driley2f@furl.net",
        "Mobile": "7-(859)418-6828",
        "DateOfBirth": "23/10/1986"
    }, {
        "id": 89,
        "Gender": "Female",
        "FirstName": "Rachel",
        "LastName": "Fuller",
        "PreferredName": "Maria",
        "Email": "mfuller2g@plala.or.jp",
        "Mobile": "1-(487)523-6136",
        "DateOfBirth": "26/06/1994"
    }, {
        "id": 90,
        "Gender": "Female",
        "FirstName": "Janice",
        "LastName": "Johnson",
        "Email": "ajohnson2h@twitpic.com",
        "Mobile": "0-(840)457-7451"
    }, {
        "id": 91,
        "Gender": "Female",
        "FirstName": "Amanda",
        "LastName": "Mccoy",
        "PreferredName": "Beverly",
        "Email": "bmccoy2i@bizjournals.com",
        "Mobile": "0-(531)261-7405",
        "DateOfBirth": "16/08/1998"
    }, {
        "id": 92,
        "Gender": "Female",
        "FirstName": "Beverly",
        "LastName": "Sullivan",
        "Email": "tsullivan2j@discuz.net"
    }, {
        "id": 93,
        "Gender": "Female",
        "FirstName": "Teresa",
        "LastName": "Meyer",
        "PreferredName": "Judy",
        "Email": "jmeyer2k@mayoclinic.com",
        "Mobile": "5-(961)879-3871",
        "DateOfBirth": "10/11/1986"
    }, {
        "id": 94,
        "Gender": "Female",
        "FirstName": "Wanda",
        "LastName": "Little",
        "PreferredName": "Judith",
        "Email": "jlittle2l@scientificamerican.com",
        "Mobile": "7-(129)990-7125",
        "DateOfBirth": "18/11/1984"
    }, {
        "id": 95,
        "Gender": "Male",
        "FirstName": "George",
        "LastName": "Rogers",
        "Email": "krogers2m@cnbc.com",
        "Mobile": "0-(009)474-6945"
    }, {
        "id": 96,
        "Gender": "Female",
        "FirstName": "Denise",
        "LastName": "Romero",
        "PreferredName": "Paula",
        "Email": "promero2n@gizmodo.com",
        "Mobile": "5-(878)712-3205",
        "DateOfBirth": "21/01/1996"
    }, {
        "id": 97,
        "Gender": "Male",
        "FirstName": "Carl",
        "LastName": "Jacobs",
        "Email": "sjacobs2o@senate.gov",
        "Mobile": "3-(825)338-0304"
    }, {
        "id": 98,
        "Gender": "Male",
        "FirstName": "John",
        "LastName": "Warren",
        "Email": "mwarren2p@cocolog-nifty.com",
        "Mobile": "6-(319)049-4262"
    }, {
        "id": 99,
        "Gender": "Female",
        "FirstName": "Cynthia",
        "LastName": "Gonzalez",
        "PreferredName": "Helen",
        "Email": "hgonzalez2q@eepurl.com",
        "Mobile": "0-(580)130-6850",
        "DateOfBirth": "31/07/1988"
    }, {
        "id": 100,
        "Gender": "Male",
        "FirstName": "Howard",
        "LastName": "Lynch",
        "Email": "llynch2r@europa.eu",
        "Mobile": "5-(788)636-8534"
    }];
    return list;

}